_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
        python_version: 3.12.7
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 7
                - 13
                - 23
                - 38
                - 55
            "4": 3.12.7
            "5": 0.19.9
            "8":
                - 1
                - 3
                - 5
            "10":
                - 20
            "12": 0.19.9
            "13": windows-amd64
batch_size:
    value: 32
dropout_rate:
    value: 0.2
epochs:
    value: 10
features:
    value: 14
lstm_layers:
    value: 2
lstm_units:
    value: 50
model_type:
    value: LSTM
optimizer:
    value: adam
sequence_length:
    value: 10
